#!/usr/bin/env node
/**
 * The `eklavya` CLI: the parts of Eklavya that make sense outside a Claude Code
 * session. The commit gate has its own POSIX script (`cli/eklavya-gate`) because
 * a git hook must not pay Node's startup cost.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { openDb } from './db.js';
import { dbPath, eklavyaHome } from './paths.js';
import { loadConfig, writeConfigFile, REPO_CONFIG_FILE, DEFAULT_CONFIG } from './config.js';
import { levelStanding } from './store.js';
import { startDashboard } from './dashboard.js';

const moduleDir = path.dirname(fileURLToPath(import.meta.url));

const USAGE = `eklavya — local learning state for agent-assisted development

Usage:
  eklavya export-rules [--out <file>]   Write the tutor pedagogy as a Cursor rules file
  eklavya config get                    Show the effective configuration
  eklavya config set <key> <value>      Change a setting (add --repo to scope it to this repo)
                                        e.g. mode ambient|enforced|off, focus project|concept|learn,
                                        cadence interleaved|end,
                                        difficulty auto|easy|medium|hard
                                        add --topic <topic> when setting focus to "learn"
  eklavya dashboard [--port <n>]        Serve the learning dashboard on localhost
  eklavya doctor                        Check that everything is wired up
  eklavya db-path                       Print the database location

Config keys: mode, focus, focus_topic, cadence, difficulty, level_up_after,
             level_up_accuracy, pass_threshold, max_questions_per_task,
             min_minutes_between_quizzes, min_minutes_between_checkpoints,
             max_new_concepts_per_session, max_stop_blocks_per_session, quiet
`;

function fail(message: string): never {
  process.stderr.write(`${message}\n`);
  process.exit(1);
}

function exportRules(args: string[]): void {
  const skillPath = path.join(moduleDir, 'assets', 'tutor-skill.md');
  if (!fs.existsSync(skillPath)) {
    fail('The bundled tutor skill is missing. Run `npm run build` in the mcp/ directory.');
  }

  const skill = fs.readFileSync(skillPath, 'utf8').replace(/^---\n[\s\S]*?\n---\n/, '');

  const rules = `---
description: Eklavya tutor — teach the concepts behind the code being written
alwaysApply: true
---

<!-- Generated by \`eklavya export-rules\`. Do not edit by hand; edit the plugin's
     skills/tutor/SKILL.md and regenerate, so Claude Code and Cursor never drift. -->

The Eklavya MCP server is available in this editor. Its tools are the source of
truth for what this developer already knows.

${skill.trim()}
`;

  const outIndex = args.indexOf('--out');
  if (outIndex >= 0) {
    const out = args[outIndex + 1];
    if (!out) fail('--out needs a file path.');
    fs.mkdirSync(path.dirname(path.resolve(out)), { recursive: true });
    fs.writeFileSync(out, rules, 'utf8');
    process.stdout.write(`Wrote ${out}\n`);
    return;
  }

  process.stdout.write(rules);
}

function configCommand(args: string[]): void {
  const [action, key, value] = args;
  const scopeRepo = args.includes('--repo');
  const resolved = loadConfig();

  if (!action || action === 'get') {
    process.stdout.write(`${JSON.stringify(resolved.config, null, 2)}\n`);
    process.stdout.write(`\nglobal: ${resolved.globalPath}\n`);
    process.stdout.write(`repo:   ${resolved.repoPath ?? '(none)'}\n`);
    return;
  }

  if (action !== 'set') fail(`Unknown config action "${action}".`);
  if (!key || value === undefined) fail('Usage: eklavya config set <key> <value>');
  if (!(key in DEFAULT_CONFIG)) {
    fail(`Unknown setting "${key}". Known: ${Object.keys(DEFAULT_CONFIG).join(', ')}`);
  }

  // `focus learn` is useless without a topic, so let one call say both rather
  // than leaving a state that the planner will only refuse later.
  const topicIndex = args.indexOf('--topic');
  const topic = topicIndex === -1 ? undefined : args[topicIndex + 1];
  if (topicIndex !== -1 && !topic) fail('--topic needs a value.');
  if (topic !== undefined && key !== 'focus' && key !== 'focus_topic') {
    fail('--topic only applies when setting focus.');
  }
  if (key === 'focus' && value === 'learn' && topic === undefined) {
    fail('focus "learn" needs a topic: eklavya config set focus learn --topic <topic>');
  }

  // A topic is always a string. Number-parsing it would turn a topic like "html5"
  // -- or worse, "2" -- into something `coerce` then silently drops.
  const isTopicKey = key === 'focus_topic';
  let parsed: unknown = value;
  if (isTopicKey) parsed = value;
  else if (value === 'true' || value === 'false') parsed = value === 'true';
  else if (value !== '' && !Number.isNaN(Number(value))) parsed = Number(value);

  const patch: Record<string, unknown> = { [key]: parsed };
  if (topic !== undefined && key === 'focus') patch.focus_topic = topic;

  let target: string;
  if (scopeRepo) {
    if (!resolved.repoRoot) fail('Not inside a git repository, so there is nowhere to write .eklavya.json.');
    target = resolved.repoPath ?? path.join(resolved.repoRoot, REPO_CONFIG_FILE);
  } else {
    target = resolved.globalPath;
  }

  writeConfigFile(target, patch);
  for (const [k, v] of Object.entries(patch)) {
    process.stdout.write(`${k} = ${JSON.stringify(v)}  ->  ${target}\n`);
  }
}

function doctor(): void {
  const file = dbPath();
  const resolved = loadConfig();
  const lines: string[] = [];
  let ok = true;

  lines.push(`home:     ${eklavyaHome()}`);
  lines.push(`database: ${file}${fs.existsSync(file) ? '' : '   (not created yet)'}`);

  try {
    const db = openDb(file);
    const concepts = (db.prepare('SELECT count(*) n FROM concepts').get() as { n: number }).n;
    const attempts = (db.prepare('SELECT count(*) n FROM attempts').get() as { n: number }).n;
    const known = (
      db.prepare('SELECT count(*) n FROM mastery WHERE score >= 0.7 AND reps >= 2').get() as { n: number }
    ).n;
    lines.push(`concepts: ${concepts}`);
    lines.push(`attempts: ${attempts}`);
    lines.push(`mastered: ${known}`);
    lines.push(`journal:  ${String(db.pragma('journal_mode', { simple: true }))}`);
    // The project's band, and the runway left in it. Read here because `doctor`
    // is where someone looks when the questions feel wrong for them.
    const standing = levelStanding(db, resolved.config, resolved.repoRoot);
    lines.push(
      `level:    ${standing.level}${
        standing.pinned
          ? ' (pinned by config — no progression)'
          : ` (${standing.counts.passed}/${standing.needed.answers} passing answers in ${standing.repo})`
      }`,
    );
    db.close();
  } catch (err) {
    ok = false;
    lines.push(`database error: ${err instanceof Error ? err.message : String(err)}`);
  }

  const fromRepo = resolved.repoPath ? ' (from this repo)' : '';
  lines.push(`mode:     ${resolved.config.mode}${fromRepo}`);
  lines.push(
    `focus:    ${resolved.config.focus}${
      resolved.config.focus === 'learn' ? ` (${resolved.config.focus_topic ?? 'no topic set'})` : ''
    }${fromRepo}`,
  );
  lines.push(
    `cadence:  ${resolved.config.cadence}${
      resolved.config.cadence === 'interleaved'
        ? ` (one question mid-task, min ${resolved.config.min_minutes_between_checkpoints}m apart)`
        : ' (all questions at the end of the task)'
    }${fromRepo}`,
  );
  if (resolved.overrides.length > 0) {
    lines.push(`overridden by repo: ${resolved.overrides.join(', ')}`);
  }

  process.stdout.write(`${lines.join('\n')}\n`);
  if (!ok) process.exit(1);
}

function dashboardCommand(argv: string[]): void {
  const i = argv.indexOf('--port');
  const port = i === -1 ? undefined : Number(argv[i + 1]);
  if (port !== undefined && !Number.isInteger(port)) {
    process.stderr.write('eklavya dashboard: --port needs a number\n');
    process.exit(1);
  }

  startDashboard(openDb(), { port }).then(
    ({ url }) => {
      process.stdout.write(`Eklavya dashboard on ${url}\nReading ${dbPath()} — press Ctrl+C to stop.\n`);
    },
    (err: Error) => {
      process.stderr.write(`eklavya dashboard: ${err.message}\n`);
      process.exit(1);
    },
  );
}

function main(): void {
  const [command, ...rest] = process.argv.slice(2);

  switch (command) {
    case 'export-rules':
      return exportRules(rest);
    case 'config':
      return configCommand(rest);
    case 'dashboard':
      return dashboardCommand(rest);
    case 'doctor':
      return doctor();
    case 'db-path':
      process.stdout.write(`${dbPath()}\n`);
      return;
    case undefined:
    case '-h':
    case '--help':
      process.stdout.write(USAGE);
      return;
    default:
      process.stderr.write(USAGE);
      process.exit(1);
  }
}

main();
