#!/usr/bin/env node
/**
 * The `eklavya` CLI: the parts of Eklavya that make sense outside a Claude Code
 * session. The commit gate has its own POSIX script (`cli/eklavya-gate`) because
 * a git hook must not pay Node's startup cost.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { openDb } from './db.js';
import { dbPath, eklavyaHome } from './paths.js';
import { loadConfig, writeConfigFile, REPO_CONFIG_FILE, DEFAULT_CONFIG } from './config.js';

const moduleDir = path.dirname(fileURLToPath(import.meta.url));

const USAGE = `eklavya — local learning state for agent-assisted development

Usage:
  eklavya export-rules [--out <file>]   Write the tutor pedagogy as a Cursor rules file
  eklavya config get                    Show the effective configuration
  eklavya config set <key> <value>      Change a setting (add --repo to scope it to this repo)
  eklavya doctor                        Check that everything is wired up
  eklavya db-path                       Print the database location

Config keys: mode, pass_threshold, max_questions_per_task,
             min_minutes_between_quizzes, max_new_concepts_per_session,
             max_stop_blocks_per_session, quiet
`;

function fail(message: string): never {
  process.stderr.write(`${message}\n`);
  process.exit(1);
}

function exportRules(args: string[]): void {
  const skillPath = path.join(moduleDir, 'assets', 'tutor-skill.md');
  if (!fs.existsSync(skillPath)) {
    fail('The bundled tutor skill is missing. Run `npm run build` in the mcp/ directory.');
  }

  const skill = fs.readFileSync(skillPath, 'utf8').replace(/^---\n[\s\S]*?\n---\n/, '');

  const rules = `---
description: Eklavya tutor — teach the concepts behind the code being written
alwaysApply: true
---

<!-- Generated by \`eklavya export-rules\`. Do not edit by hand; edit the plugin's
     skills/tutor/SKILL.md and regenerate, so Claude Code and Cursor never drift. -->

The Eklavya MCP server is available in this editor. Its tools are the source of
truth for what this developer already knows.

${skill.trim()}
`;

  const outIndex = args.indexOf('--out');
  if (outIndex >= 0) {
    const out = args[outIndex + 1];
    if (!out) fail('--out needs a file path.');
    fs.mkdirSync(path.dirname(path.resolve(out)), { recursive: true });
    fs.writeFileSync(out, rules, 'utf8');
    process.stdout.write(`Wrote ${out}\n`);
    return;
  }

  process.stdout.write(rules);
}

function configCommand(args: string[]): void {
  const [action, key, value] = args;
  const scopeRepo = args.includes('--repo');
  const resolved = loadConfig();

  if (!action || action === 'get') {
    process.stdout.write(`${JSON.stringify(resolved.config, null, 2)}\n`);
    process.stdout.write(`\nglobal: ${resolved.globalPath}\n`);
    process.stdout.write(`repo:   ${resolved.repoPath ?? '(none)'}\n`);
    return;
  }

  if (action !== 'set') fail(`Unknown config action "${action}".`);
  if (!key || value === undefined) fail('Usage: eklavya config set <key> <value>');
  if (!(key in DEFAULT_CONFIG)) {
    fail(`Unknown setting "${key}". Known: ${Object.keys(DEFAULT_CONFIG).join(', ')}`);
  }

  let parsed: unknown = value;
  if (value === 'true' || value === 'false') parsed = value === 'true';
  else if (value !== '' && !Number.isNaN(Number(value))) parsed = Number(value);

  let target: string;
  if (scopeRepo) {
    if (!resolved.repoRoot) fail('Not inside a git repository, so there is nowhere to write .eklavya.json.');
    target = resolved.repoPath ?? path.join(resolved.repoRoot, REPO_CONFIG_FILE);
  } else {
    target = resolved.globalPath;
  }

  writeConfigFile(target, { [key]: parsed });
  process.stdout.write(`${key} = ${JSON.stringify(parsed)}  ->  ${target}\n`);
}

function doctor(): void {
  const file = dbPath();
  const lines: string[] = [];
  let ok = true;

  lines.push(`home:     ${eklavyaHome()}`);
  lines.push(`database: ${file}${fs.existsSync(file) ? '' : '   (not created yet)'}`);

  try {
    const db = openDb(file);
    const concepts = (db.prepare('SELECT count(*) n FROM concepts').get() as { n: number }).n;
    const attempts = (db.prepare('SELECT count(*) n FROM attempts').get() as { n: number }).n;
    const known = (
      db.prepare('SELECT count(*) n FROM mastery WHERE score >= 0.7 AND reps >= 2').get() as { n: number }
    ).n;
    lines.push(`concepts: ${concepts}`);
    lines.push(`attempts: ${attempts}`);
    lines.push(`mastered: ${known}`);
    lines.push(`journal:  ${String(db.pragma('journal_mode', { simple: true }))}`);
    db.close();
  } catch (err) {
    ok = false;
    lines.push(`database error: ${err instanceof Error ? err.message : String(err)}`);
  }

  const resolved = loadConfig();
  lines.push(`mode:     ${resolved.config.mode}${resolved.repoPath ? ' (from this repo)' : ''}`);

  process.stdout.write(`${lines.join('\n')}\n`);
  if (!ok) process.exit(1);
}

function main(): void {
  const [command, ...rest] = process.argv.slice(2);

  switch (command) {
    case 'export-rules':
      return exportRules(rest);
    case 'config':
      return configCommand(rest);
    case 'doctor':
      return doctor();
    case 'db-path':
      process.stdout.write(`${dbPath()}\n`);
      return;
    case undefined:
    case '-h':
    case '--help':
      process.stdout.write(USAGE);
      return;
    default:
      process.stderr.write(USAGE);
      process.exit(1);
  }
}

main();
